### ISSUE TITLE
possible to get an online demo?

### ISSUE THREAD

**Issue by winkler1** [teamstrobe/watchlist#1]
Or at least a screenshot. Would love to add to react.rocks, sounds sweet :)

**Comment by joecritch** [comment]
@winkler1 Sure thing, I've added a screenshot. I'll ping you when user authentication is in place so that a demo is do-able. (Otherwise I'd need to give my login details away!!)

**Comment by joecritch** [comment]
@winkler1 Demo here: http://teamstrobe.github.io/watchlist/ ... I'll probably make a local storage / public search adaptor at some point too, so people can get stuck in right away
